server :
 port: 3031

# Configurações do H2 Database
spring:
 h2:
  console:
   enabled: true
   path: /h2-console
 datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password: 
    driverClassName: org.h2.Driver
 jpa:
    hibernate:
      ddl-auto: update 
    properties:
     hibermate:
     show-sql: false